- CMakeLists.txt
- src/Color.hpp
- src/Font.hpp
- src/SDLFacade.hpp
- src/SdlFacade.hpp
Added interface for SDL2 facade + color.hpp and font.hpp
> Wouter martijn sdl facade

- src/DoubleCoordinate.hpp
- src/PointOfView.cpp
- src/PointOfView.hpp
- src/RaycastingVector.hpp
- src/Vector.hpp
This adds the Point of View class and all the required structs
> feat: add PoV

- .gitignore
- CMakeLists.txt
- src/Color.hpp
- src/DoubleCoordinate.hpp
- src/Font.hpp
- src/PointOfView.cpp
- src/PointOfView.hpp
- src/RaycastingVector.hpp
- src/SDLFacade.cpp
- src/SDLFacade.hpp
- src/main.cpp
het tekenen van een lijn is ondersteund. colors is nog niet gekoppeld
> Wouter drawline sdl

- src/Color.hpp
- src/TileObject.cpp
- src/TileObject.hpp
- src/WorldObject.cpp
- src/WorldObject.hpp
TileObject() cpp & hpp files
WorldObject() cpp & hpp files
> Sander jelmer wordl tileobject

- src/RayCastingTypes.hpp
- src/Raycasting.cpp
- src/Raycasting.hpp
- src/WorldObject.hpp
* Adds docs
* Removes duplicate structs (or typedeffed them)
* Adds _correct_line function, to correct out of bounds coords
> Jorg thomas raycasting engine

- src/Raycasting.cpp
- src/Raycasting.hpp
- src/SDLFacade.cpp
- src/SDLFacade.hpp
- src/TileObject.cpp
- src/TileObject.hpp
- src/WorldObject.cpp
- src/WorldObject.hpp
This PR contains refactors for all the Engine components, since a lot of issues actually got through the reviewing process (BOO ME)
> Thomas style refactors

- .travis.yml
Add Travis CI build integration
> Thomas travis

- CMakeLists.txt
- src/Game.cpp
- src/Game.hpp
- src/Raycasting.cpp
- src/Raycasting.hpp
- src/SDLFacade.cpp
- src/SDLFacade.hpp
This adds the Game class, which will be the actual game's entry point and which contains the main game loop.
> Jorg thomas game class

- src/engine/SDLFacade.cpp
added the documentation for all methods made by Wouter in the SDL_Facade
(the methods made by Martijn are already made, but in a different branch)
> Wouter sdlfacade documentation

- src/gamelogic/Game.cpp
- src/gamelogic/Level.cpp
all code documentation that was not implemented
> code documentation

- src/engine/SDLFacade.cpp
Added some code as well. (saves me from creating two pull-requests <3)
> fix: Memory leaks in init and destructor. (+ code-doc)

- CMakeLists.txt
- src/config.hpp
- src/engine/SDLFacade.cpp
> refactor: add config file and extract window name to it

- src/engine/SDLFacade.cpp
- src/engine/SDLFacade.hpp
can load an image and return a list of pixels in Uint32 format
> Wouter load image

- src/engine/SDLFacade.hpp
This slightly cleans up the SDL_Facade's .hpp file
> Thomas sdl facade refactor

- src/engine/FPScounter.cpp
> fix: initialise Fpscounter value

- src/gamelogic/Level.cpp
TODO #33
niet alle constructors zouden gedefineerd zijn dus voor duidelijkheid staan ze nu alle 3 bovenaan in cpp file
> refactor: all constructors defined

- src/engine/KeyStrokes.hpp
- src/engine/SDLFacade.cpp
- src/engine/SDLFacade.hpp
- src/engine/domain/World.hpp
- src/engine/interface/Collection.cpp
- src/engine/interface/Collection.hpp
- src/engine/interface/Handleable.hpp
- src/engine/raycasting/Raycasting.cpp
- src/gamelogic/Level.cpp
- src/gamelogic/Level.hpp
- src/gamelogic/Player.cpp
- src/gamelogic/Player.hpp
- src/gamelogic/state/CreditState.cpp
- src/gamelogic/state/CreditState.hpp
- src/gamelogic/state/HelpState.cpp
- src/gamelogic/state/HelpState.hpp
- src/gamelogic/state/LoadState.cpp
- src/gamelogic/state/LoadState.hpp
- src/gamelogic/state/Menu.cpp
- src/gamelogic/state/Menu.hpp
- src/gamelogic/state/MenuState.cpp
- src/gamelogic/state/MenuState.hpp
- src/gamelogic/state/PauseState.cpp
- src/gamelogic/state/PauseState.hpp
- src/gamelogic/state/RunState.cpp
- src/gamelogic/state/RunState.hpp
- src/gamelogic/state/StartUpState.cpp
- src/gamelogic/state/StartUpState.hpp
This cleans up the messy timesincelastpress code, makes Input extendable, and makes the menu actually responsive (since Bob commented on it).
> Thomas input responsiveness

- src/engine/SDLFacade.cpp
- src/engine/SDLFacade.hpp
- src/engine/domain/TileObject.cpp
- src/engine/domain/TileObject.hpp
- src/gamelogic/Level.cpp
- src/gamelogic/Tile.cpp
- src/gamelogic/WorldParser.cpp
- src/gamelogic/state/CreditState.cpp
- src/gamelogic/state/HelpState.cpp
- src/gamelogic/state/LoadState.cpp
- src/gamelogic/state/MenuState.cpp
- src/gamelogic/state/PauseState.cpp
- src/gamelogic/state/StartUpState.cpp
- src/util/UnusedMacro.hpp
See commit msg for more info for al the fixes
> Jorg warnings, fixes #55 and other compiler warnings

- src/engine/AssetsManager.cpp
- src/engine/AssetsManager.hpp
- src/engine/domain/TileObject.cpp
- src/engine/domain/TileObject.hpp
- src/engine/domain/World.hpp
- src/engine/raycasting/Raycasting.cpp
- src/gamelogic/Tile.cpp
- src/gamelogic/Tile.hpp
- src/gamelogic/exceptions/InvalidTextureException.cpp
- src/gamelogic/exceptions/InvalidTextureException.hpp
> Jelmer settexture

- src/engine/domain/TileObject.cpp
- src/engine/domain/TileObject.hpp
- src/engine/domain/TileTrigger.cpp
- src/engine/domain/TileTrigger.hpp
- src/gamelogic/Player.cpp
- src/gamelogic/Player.hpp
- src/gamelogic/WorldParser.cpp
- src/gamelogic/WorldParser.hpp
- src/gamelogic/state/LevelWinState.cpp
- src/gamelogic/state/LevelWinState.hpp
> Jelmer gaemwinstate

- src/engine/domain/TileObject.cpp
- src/engine/domain/TileObject.hpp
- src/gamelogic/Level.cpp
- src/gamelogic/Level.hpp
- src/gamelogic/Player.cpp
- src/gamelogic/Player.hpp
- src/gamelogic/Tile.cpp
- src/gamelogic/Tile.hpp
- src/gamelogic/TileTrigger.cpp
- src/gamelogic/TileTrigger.hpp
- src/gamelogic/WorldParser.cpp
- src/gamelogic/WorldParser.hpp
Tested this, this doesn't break our code 😆
> feat: Tiletriggers to GameLogic instead of Engine Logic

- res/TestMap.tmx
- src/gamelogic/WorldParser.cpp
- src/gamelogic/WorldParser.hpp
Able to make a trigger in tiled called DoorTrigger and get's placed as an
action trigger in the game. (also functions as a template for all other triggers that can be added)
> feature: Tiled trigger in game

- src/gamelogic/Player.cpp
- src/gamelogic/Player.hpp
> feat: action can now only be triggered once per press

- src/engine/raycasting/Raycasting.cpp
> Thomas raycaster refactor

- src/engine/AssetsManager.cpp
- src/engine/AssetsManager.hpp
Hocus pocus spilatus pas, ik wou dat de memory leak weg was!
> Thomas assetsmanager memoryleaks

- src/gamelogic/WorldParser.cpp
- src/gamelogic/rapidXML/RapidXMLAdapter.cpp
> refactor: fix signed/unsigned comparison warnings

- Makefile
This makes sure that the res directory is copied whenever anything is run from the Makefile. Which in turn makes sure that when you edit the map in tiled, rerunning the program will load the edited map, and not the old one.
Closes #115
> Thomas res
